### ISSUE TITLE
Compare Julia and C++ versions

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#101]
Write thorough tests to ensure we get the exact same results. (Looks like we do, but let's be formal about it.)

**Comment by rodluger** [comment]
@ericagol If you have time, could you clean up the `julia/` folder a bit? Perhaps place the tests in separate directories, rename `sn_bigr` since it's no longer just for large `r`, and expand the `README` to describe what each of the files does? Then I can create some simple tests to compare our results.

**Comment by ericagol** [comment]
@rodluger Yes, I've been meaning to do that.  I've been thinking about a couple of other issues:

1.  The `Julia` implementation just computes the `s_n` functions, and not the entire map (nor any of the other tremendous functionality you have in `s^TAR'Ry` package.
2.  Apparently `Julia` packages require a separate repository, which is why we created `celerite.jl` as a separate repository from `celerite`.
3.  The primary application of the `Julia` code so far is to compute the polynomial limb-darkening model, which I've added a description of to the `limbdark` paper.

So, I'm wondering whether it would make sense to move the `Julia` code to the `limbdark` repository?

**Comment by ericagol** [comment]
@rodluger Okay, I've moved the code, and reorganized the `limbdark` structure some.

**Comment by rodluger** [comment]
@ericagol Ok, awesome! Can I go ahead and delete the `julia` folder in `starry`?

**Comment by ericagol** [comment]
I already deleted it (perhaps I need a pull request?).
