### ISSUE TITLE
Deriving surface brightness of the Earth from EPOXI moon occultation

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#11]
Figure 6 reminded me that it would be cool to see what could be inferred from the color-dependent EPOXI observation of the Earth transited by the Moon:

https://www.nasa.gov/topics/solarsystem/features/epoxi_transit.html

Here's a four-color version of the movie:

https://www.dropbox.com/s/yykr3n91zqmf0oq/Earth4_4colors-1202.mov?dl=0

The one challenge, of course, is that the Earth's emission is due to the convolution of the albedo pattern with the illumination profile of the Sun (and perhaps a scattering function?).

-Eric

**Comment by rodluger** [comment]
I can't currently model this with `starry` because of the elliptical shape of the terminator. But I'm pretty sure that the line integral of my Greens polynomials about the terminator is (surprise!) just an elliptic integral, so I think we'll eventually be able to do this. I'm planning on a second paper down the line on occultations/phase curves in reflected light, so this would be a perfect thing to tackle then.
