### ISSUE TITLE
We might need c++11 support

### ISSUE THREAD

**Issue by dfm** [rodluger/starry#135]
The unix compilers that conda-forge uses are ancient and it doesn't look like we'll be able to use c++14...

It looks like all that is needed is to update the Table initialization in starry/tables.h, but I don't understand well enough what is going on there to do it myself.

**Comment by dfm** [comment]
I started a branch to try this out: https://github.com/rodluger/starry/tree/c++11

**Comment by rodluger** [comment]
Ah, bummer. Yes, I switched to c++14 so I could use for loops and other
stuff inside constexpr. There's a way to do all this with c++11 but it's
pretty ugly. I can look into it later today if you don't figure it out by
then!

**Comment by dfm** [comment]
OK. I definitely don't know what's going on there, so I'll leave it up to you to re-write :-) Sorry!

**Comment by rodluger** [comment]
No worries. I think I figured out how to do it, but man, it's ugly. I'll
push soon.

**Comment by rodluger** [comment]
@dfm [Womp womp](https://travis-ci.org/rodluger/starry/builds/404250991?utm_source=email&utm_medium=notification). I figured out how to get the code to compile with C++11 using variadic templates and it compiles fine with `clang` on a Mac. But it turns out that gcc-4.9 and below [have a bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52892) that was fixed in gcc-5.0. I imagine that we can't use gcc-5.0 on conda forge (otherwise we'd probably have c++14 support), so I'm back at square one. I'm going to just revert to the old school way of tabulating all the square roots and factorials by hand...

**Comment by rodluger** [comment]
@dfm Working now with C++11. Do you need me to merge this into master?

**Comment by rodluger** [comment]
@dfm Can you also check that what I did [here](https://github.com/rodluger/starry/commit/770a4dd7f204125e15e1de8ab24d1297eb1a10f3#diff-2eeaed663bd0d25b7e608891384b7298R111) is correct? Check out my comment [here](https://github.com/rodluger/starry/commit/9de683cc9bc2194ab544b4f688a64649b8901cd9#comments).

**Comment by dfm** [comment]
Yes! Sorry I was traveling. This looks great! I'll give it a try on conda-forge and get back to you.

**Comment by dfm** [comment]
OK. Sweet! It looks like that worked: https://github.com/conda-forge/staged-recipes/pull/6287

It might be easiest if you either replace the current 0.1.1 or do a release for 0.1.2.

**Comment by rodluger** [comment]
@dfm Done. Master is now up to date, I've created a branch called v0.1.2 and a release with the same name, and uploaded that version to PyPI.

**Comment by rodluger** [comment]
@dfm When does the package actually become installable via conda?

**Comment by dfm** [comment]
It normally takes a few hours in my experience. I'll let you know.

**Comment by rodluger** [comment]
thanks!
