### ISSUE TITLE
Why is julia so much faster?

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#163]
This is a plot of speed tests for a quadratically limb-darkened transit, comparing `starry`, `batman`, and Eric's `limbdark` julia code:
![image](https://user-images.githubusercontent.com/9323819/47028985-7ec4ca80-d138-11e8-98f4-f82cb7c61fcc.png)
My non-gradient computations are comparable in speed to Eric's (albeit slower by several tens of percent), but my gradient ones are super slow. Granted I am still using autodiff, while Eric is computing derivatives analytically. But his computation with gradients is *still* faster than mine without gradients, which is crazy! @dfm can you help audit my code at some point to speed it up?

**Comment by ericagol** [comment]
@rodluger Could it simply be due to using autodiff?  One thing I found in my implementation was that allocating memory can take time, so if I pre-allocate arrays with a structure, this sped up my code.  However, with autodiff I'm not sure how to pre-allocate memory, and the autodiff'ed code may have even more memory allocation since it needs to track and propagate gradients.

It might also be interesting to compare our codes for the higher-order limb-darkened case as well.

**Comment by rodluger** [comment]
The julia and cpp codes are now comparable in speed on the `v2` branch.
