### ISSUE TITLE
Fix normalization for spectral maps

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#171]
When using multi-wavelength `starry`, the map normalization at each wavelength (i.e., the spectrum) is lost when loading a Healpy array, since `starry` normalizes the map to have `y[0] = 1`. This is silly and we should either fix it or provide an easy, intuitive way to preserve the normalization. Here's a notebook with a function that does just that.
[HealpixFix.ipynb.zip](https://github.com/rodluger/starry/files/2502138/HealpixFix.ipynb.zip)

**Comment by rodluger** [comment]
@jlustigy Did my hack work for what you were doing? Should I go ahead and implement it in `starry`?

**Comment by jlustigy** [comment]
Hey @rodluger, It works perfectly with `starry.Map`: 

![figure_1](https://user-images.githubusercontent.com/8882466/47683807-f27dc300-db8d-11e8-9fbe-ceaa7915e179.png)

But it doesn't work yet with `starry.kepler.Secondary`. I tried applying your fix to the planet map and then exchanged the Y_{0,0} coefficients with the luminosity to avoid the `RuntimeError: Bodies instantiated via the Kepler module must all have Y_{0, 0} = 1. You probably want to change the body's luminosity instead.`:

```python
# Create starry planet
planet = starry.kepler.Secondary(lmax=lmax, nwav=Nlamlo)

# Create map in starry
map = starry.Map(lmax=lmax, nwav=Nlamlo)

# Create empty 2d array of spherical harmonic coefficients
y = np.zeros_like(map.y)

# Loop over lightcurve wavelengths
for n in range(Nlamlo):

    # Fill coeffs at this wavelength
    y[:, n] = expand_hp(spec2d[:,n], lmax=map.lmax)

# Apply new map to starry planet object
planet[:, :] = y

# NEW: Exchange the y_{0,0} with the luminosity
planet.L = planet[0,:]

# NEW: Set y_{0,0} to unity to make starry happy
planet[0,:] = np.ones(Nlamlo)
```

However, I must be missing something (probably pretty trivial) here because I do not recover the input spectra:
![figure_2](https://user-images.githubusercontent.com/8882466/47684425-1b9f5300-db90-11e8-9082-0bb96062c522.png)

**Comment by rodluger** [comment]
Cool! Try dividing your map by the y_0 coefficient before feeding it to
starry, then setting the luminosity to that value. Does that work?

**Comment by jlustigy** [comment]
That doesn't seem to do it 😿 

I replaced the last line in my above code with:
```python
# NEW: divide out y_0 coeff to (a) normalize and (b) set y_{0,0} to unity to make starry happy 
planet[:, :] = planet[:, :] / planet[0, :]
```

**Comment by rodluger** [comment]
@jlustigy Can you post a MWE for me to play with?

**Comment by rodluger** [comment]
@jlustigy Actually, instead of what you tried last, can you try simply this:
```python
planet[:, :] = y
planet.L = y[0, 0]
```

**Comment by jlustigy** [comment]
This gives the following error: 
```
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: starry._starry_spectral_64.kepler.Body, arg1: numpy.ndarray[float64[m, 1]]) -> None

Invoked with: <starry.kepler.Secondary(lmax=18, nwav=10, multi=False)>, 1.6115455088995327
```

This is likely because `planet.L` is a wavelength-dependent vector and `y[0,0]` is a scalar, but if I use `y[0, :]` then we are back to where we started, with a non-unity `y[0]`. 

As far as a MWE, the example I am working on is located on the gen_lightcurves branch of the [eigenspectra](https://github.com/multidworlds/eigenspectra) project. This fix appears at [this line](https://github.com/multidworlds/eigenspectra/blob/gen_lightcurves/gen_lightcurves.py#L333), and you can run `gen_lightcurves.py` as a script to produce the debugging plot I keep referring to in this thread.

**Comment by rodluger** [comment]
@jlustigy I fixed it for you: https://github.com/multidworlds/eigenspectra/pull/36
It was just a matter of multiplying the intensity by the luminosity when plotting. Let me know if this looks good, and if so, I'll patch `starry` itself. I can make the default behavior to auto-set the luminosity when a map is loaded via the Secondary class.

**Comment by jlustigy** [comment]
@rodluger awesome! Thank you!
