### ISSUE TITLE
Can I have a Kepler Tertiary?

### ISSUE THREAD

**Issue by christinahedges** [rodluger/starry#193]
Hey Rodrigo,

Just a quick question. There is a `starry.Kepler.primary` and a `starry.Kepler.secondary`...is it possible for there to be a `starry.Kepler.tertiary` (moon) within the framework of starry? I would like to create a moon transit model, but I would like to capitalize on the speed gains from the starry analytic method. 

Any chance this is [already] possible? 
C

**Comment by rodluger** [comment]
Unfortunately that would require a significant rewrite. I'm slowly working
on it, though. My plan is to create an abstract Body class whose orbit is
controlled by an NBody integrator like REBOUND, so then you can do all
sorts of nested orbits.

Currently, though, you could just instantiate 3 Map classes, work out their
Cartesian positions as a function of time with a simple Kepler Ian solver,
and call each of their flux methods, including the occultor position if
there's an occultation. The only issue with this is that starry does not
currently handle multi-body occultations. For instance, if the moon occults
the planet while the planet is transiting, you'll get the wrong stellar
flux. Again, my plan is to fix this: the problem is still analytical, just
a bit trickier.

You could check out Andras Pal's code (Pal 2012) or David Kipping's Luna
code (Kipping 2012), which work in the three-body occultation case (and are
analytical). And I think Kipping's code has an orbital solver, but I don't
know if it's open source. But keep in mind that none of the bodies can have
complicated maps: I think simple limb darkening laws are all that these
codes can do.

**Comment by christinahedges** [comment]
> My plan is to create an abstract Body class whose orbit is controlled by an NBody integrator like REBOUND, so then you can do all sorts of nested orbits.

That sounds amazing! I would subscribe to this functionality!

> The only issue with this is that starry does not currently handle multi-body occultations.

I see, and I guess for moons this is pretty important, I might hold off then and use one of the other codes you've suggested. Of course, it's nice in starry that you provide gradients for fast fitting! 

Thanks for the quick response, I know when you give me an inch I'm going to ask for a mile, starry as it stands is already a brilliant package!
