### ISSUE TITLE
Modeling high eccentricity planets (solver not converging)

### ISSUE THREAD

**Issue by mason-macdougall** [rodluger/starry#201]
I'm trying to use starry to model a planet with an eccentricity of ~0.84, but I keep running into the error message of "The Kepler solver did not converge." 

In particular, the error is flagged anytime I cross from ecc = 0.71428 to ecc = 0.71429 regardless of what I set for the other parameters. I have not yet looked into the source code, so I was just wondering if anyone else has run into this issue or if anyone has suggestions about how to work around this problem. Thanks in advance for any help!

Here is the code that I'm currently using (the parameters are arbitrary besides ecc):

import starry
star = starry.kepler.Primary()

from starry.kepler import Primary, Secondary, System

# Instantiate the star
star = starry.kepler.Primary()

star[1] = 0.4
star[2] = 0.25

# Instantiate the planet
planet = starry.kepler.Secondary()
planet.tref = 0
planet.porb = 1
planet.r = .1
planet.a = 10
planet.inc = 90
planet.w = 0

#planet.ecc = ecc_true
planet.ecc = 0.71429

# Instantiate the system
system = starry.kepler.System(star, planet)

# Compute and store the light curve
time = np.linspace(-15, 15, 100000)
system.compute(time)
flux_starry = system.lightcurve

fig, ax = plt.subplots(1, figsize=(14, 6))
ax.set_xlim([-1, 1])
ax.set_xlabel('Time [days]', fontsize=16)
ax.set_ylabel('System Flux', fontsize=16)
ax.plot(time, system.lightcurve)

**Comment by rodluger** [comment]
Hi @mason-macdougall, thanks for pointing this out. The issue is the default tolerance of the Kepler solver is too high, and because of floating point error, the Kepler solver will never reach that tolerance for very high eccentricity. I patched the code on the master branch, so just run
```
pip install git+https://github.com/rodluger/starry
```
to re-install (might take a few minutes). You may have to uninstall your current version first.

I tested your code and it works up to an eccentricity of 0.97. If you exceed that, you'll have to [relax the tolerance](https://github.com/rodluger/starry/blob/435578167874d71e9e81d1f98984cdfc8115207f/starry/utils.h#L46) or increase the [number of iterations](https://github.com/rodluger/starry/blob/435578167874d71e9e81d1f98984cdfc8115207f/starry/utils.h#L41). These are compiler macros, so set them by passing them as environment variables before installing, i.e.,
```
STARRY_KEPLER_TOL=1e-10 pip install git+https://github.com/rodluger/starry
```
But you shouldn't have to do that if `e < 0.98`.

**Comment by mason-macdougall** [comment]
@rodluger Awesome, thanks so much!
