### ISSUE TITLE
Rotational broadening line spread distribution in RV mode

### ISSUE THREAD

**Issue by gully** [rodluger/starry#205]
Is there a method to compute the flux-weighted velocity distribution of the map?  In other words, this is the line-profile of a spectral line expressed in velocity units.  Should just be (integral of the map times v dv) divided by (integral of the map).  Thanks!

**Comment by rodluger** [comment]
Yep! It's in the dev branch. Check out [this notebook](https://github.com/rodluger/starry/blob/dev/notebooks/RossiterMcLaughlin.ipynb).

**Comment by gully** [comment]
Awesome notebook.  I looked there and didn't see quite what I'm looking for.  You're showing the disk-integrated mean radial velocity as a scalar $\bar v_z$.  I'm looking for the "velocity distribution function" or rotational line spread function.  I think I wrote the integral wrong in the comment above.  It should be the integral of velocity map over the solid angle of the disk yielding the distribution function f(v).  Does that make sense?

**Comment by gully** [comment]
By the way, the reason I'm asking is that you can imagine doing Doppler imaging on observed spectral line shapes.  I'm imagining a drop-in replacement for the static rotational broadening functions, with an analytic solver for the map that gives rise to the appearance of a given spectral line spread function.  If you embed this solver into Starfish, which already fits for vsini, you could imagine a profile likelihood for the map that in turn gets convolved with all the high resolution synthetic spectral model lines to produce  a rotationally broadened spectrum.  Except now a uniformly illuminated disk is not assumed, and the positions and sizes of starspots can be inferred.

**Comment by rodluger** [comment]
Ah, you must mean [these functions](https://github.com/rodluger/paparazzi/blob/master-pdf/tex/figures/kT.pdf). These are the rotation broadening functions corresponding to each of the spherical harmonics. The total broadening function due to a map with arbitrary surface features is just a linear combination of these.

Computing them is not trivial, but I did find a closed form solution for the case where there's no differential rotation or convective blueshift. (Those effects can be incorporated but they almost certainly make the Ylm integrals impossible to integrate analytically. I'm exploring fast numerical methods, though, so stay tuned).

This is not implemented in `starry` yet; I'm developing this stuff in a [separate repo](https://github.com/rodluger/paparazzi/). It will make it into `starry` once I code it all up in C/Theano, which will probably take me 1-2 months.

Have a look at the [paper draft](https://github.com/rodluger/paparazzi/raw/master-pdf/tex/ms.pdf) and let me know if this is what you're thinking about, and if you have any comments/questions!

**Comment by gully** [comment]
Yes, this is exactly what I'm thinking about, awesome!  Ok, glad to see you are working on this, and that it's so mature!!

A key question is what is the "right way" to incorporate Doppler imaging into a likelihood function for panchromatic high resolution spectral data.  In other words, how to pool the nearly-exactly repetitive Doppler imaging inference for many different spectral lines spanning a wide bandwidth (e.g. UV - IR).  The same coarse line spread function structures should be stamped into each spectral line, but the contrast or coefficients would induce wavelength-dependent perturbations, as in starspots or depth-dependent clouds on brown dwarfs.
