### ISSUE TITLE
Rodrigo doesn't understand consts in C++

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#21]
Can someone check my code to see where I should and shouldn't precede declarations with `const`? Does it really matter, particularly if we're going to autodiff stuff in the future? I haven't at all been consistent with my usage.

**Comment by dfm** [comment]
I don't think that `const`s will make too much of a difference, but the thing that *will* help is passing by reference instead of value. For example in [rotation.h](https://github.com/rodluger/starry/blob/master/starry/rotation.h#L45), I would replace:

```c++
void dlmn(int l, T s1, T c1, T c2, T tgbet2, T s3, T c3, Matrix<T>* D, Matrix<T>* R) 
```

by 

```c++
void dlmn(int l, const T& s1, const T& c1, const T& c2, const T& tgbet2, const T& s3, const T& c3, Matrix<T>* D, Matrix<T>* R) 
```

The way that you have it written, it is copying `s1`, etc., but C++ has the feature that it can pass by reference without changing your code. This doesn't really matter when `T` is `double`, but it will if you have larger types. Similarly, you *could* change `Matrix<T>*` to `Matrix<T>&` and use `D` and `R` as values instead of pointers, but this probably won't make any performance difference.

**Comment by rodluger** [comment]
Nice, thanks for catching those. Will do.
