### ISSUE TITLE
Physical star spot modeling with limb darkening 

### ISSUE THREAD

**Issue by TakuNishiumi** [rodluger/starry#220]
Hello. 
`Starry` is very useful and convenient for me. Thank you.

Now, I am trying to model star spots.
For physical modeling, I would like to compare starry's gaussian amplitude(`add_gaussian()`) and star spot temperature.
I think we can compute it by comparing intensity from black body and a value of star spot model.
(For example, if the star spot locates at x=0, y=0, we can get the amplitude value of the star spot by using `map(x=0, y=0)` in https://rodluger.github.io/starry/v0.3.0/tutorials/basics1.html#Using-starry)

However, If the star have some star spots, the amplitude was tempted by normalization.
How can I get this value?
I came up with two ideas.
1. Make a new  `map(lat, lon)` option
2. Make a new option to prohibit a normalization.
I prefer No.2, because this make us easy to set up the desired star spots.

Do you have any ideas to solve this?

Thank you.

**Comment by TakuNishiumi** [comment]
![starry_many_star_spot](https://user-images.githubusercontent.com/38071139/70405558-f2ceda00-1a80-11ea-8643-599ae1f9d2b1.png)

**Comment by rodluger** [comment]
Hi @TakuNishiumi, if I understand your problem correctly, it's difficult to get the actual intensity at the center of the spot when limb darkening is present, since the normalization is different. Is that right?

Version `1.0` of the code fixes some issues with the normalization of limb darkened maps and implements a new spot routine called `add_spot`. As of yesterday, this is the version on the `master` branch of the repository, (and should also be the version on `pip` very soon). If you upgrade to that version, you might have an easier time with what you're trying to do.

I put together a tutorial on how to add spots [here](https://rodluger.github.io/starry/latest/notebooks/StarSpots.html), so please check it out when you get a chance. Note that you can now either specify an amplitude (equal to the change in the total luminosity of the map due to the spot) **or** an intensity (equal to the change in the intensity of the map at the center of the spot). The second option might be exactly what you want.

Note a few other things:
* The new way of computing the intensity of a map is to do `map.intensity()` instead of calling the map object directly
* The arguments to the intensity are `lat` and `lon` (as you requested) instead of `x` and `y`
* You can pass `limbdarken=False` to `map.intensity()` to temporarily disable limb darkening for that computation

There are some other [major changes](https://rodluger.github.io/starry/latest/changes.html) in version `1.0` that you should read about as well.

Let me know if this is helpful or if you have suggestions on how to improve the spot modeling feature.

**Comment by TakuNishiumi** [comment]
Thank you very much @rodluger !
Your new functions and changes are very convenient.
I think these changes make us easy to model physical star spots.

I will try to model by using new functions.
If I face some problem with modeling starspot or I come up with new ideas to improve starspot, I will let you know.

Thank you very much.
Taku Nishiumi

**Comment by TakuNishiumi** [comment]
![starry2](https://user-images.githubusercontent.com/38071139/70608273-32452400-1c43-11ea-8c1c-91f133ba295f.png)

I made two same starspots at the symmetrical location.
I realized that these intensities were different. I also tried `limbdarken=False`, but the result didn't change.
I confirmed it returns the same values when I use `amp` instead of `intensity`.

I couldn't understand the whole of starry, so I might make some mistakes.

**Comment by rodluger** [comment]
Hi @TakuNishiumi, thanks for pointing this out. This is expected behavior, but I agree that it is confusing. When you add a spot and specify `intensity=-0.1`, you're telling `starry` to decrease the intensity at the location of the spot by 10 percent. But when you add the first spot to the map, the intensity changes *everywhere*, since the spot is modeled as a gaussian. When you add the second spot, you're telling `starry` to again decrease the intensity by 10 percent relative to the local intensity, which is now *slightly different* because of the presence of the first spot.

I added an option to `add_spot` called `relative`, which by default is True. In this case, you get the current behavior: the fractional change due to the spot is relative to the *current* map. To get the behavior you want, set `relative` to False. This means the fractional change due to the spot will be relative to the *original* map. See [this test](https://github.com/rodluger/starry/blob/af8f7c01ccad4e09d5321888091d775aa12b1ecc/tests/greedy/test_spot.py#L51-L80) for more details.

Note that limb darkening is always ignored when computing these relative changes.

Please let me know if this fixes your issue or if you have other suggestions!

**Comment by TakuNishiumi** [comment]
Hi @rodluger, Thank you.
Now, I understood the specification of the `add_spot(intensity= )`.

Added option is very nice!
I tried it and confirmed my issue was solved.
Thank you for your kindness and quick responses.

**Comment by TakuNishiumi** [comment]
![starry3](https://user-images.githubusercontent.com/38071139/70694359-c3c79b00-1d02-11ea-9536-804b940cadfe.png)

**Comment by rodluger** [comment]
Awesome, thanks for helping me debug this.
