### ISSUE TITLE
Numerical instabilities with occultations of very high order maps

### ISSUE THREAD

**Issue by fbartolic** [rodluger/starry#236]
Hi Rodrigo, I noticed that flux sometimes diverges for occultations in both emitted and reflected light with very high order maps (l > 20). Here's a reproducible example:
```Python
map = starry.Map(ydeg=25, reflected=False)
map.add_spot(amp=0.01, sigma=0.01, lat=41., lon=20.)

xo = np.linspace(-1, 1, 100)
yo = np.linspace(-0.08, -0.132, 100)
zo = np.ones(len(xo))
ro = 0.8552
theta = np.linspace(28.5, 28.7, 100)

flux = map.flux(theta=theta, xo=xo, yo=yo, zo=zo, ro=ro)

fig, ax = plt.subplots(2, 1, figsize=(5, 5))

ax[0].set_xlim(-1.1, 1.1)
ax[0].set_ylim(-1.1, 1.1)
ax[0].axis("off")
ax[0].imshow(map.render(), origin="lower", cmap="plasma", extent=(-1, 1, -1, 1))
npts = len(xo)
for n in list(range(0, npts, npts // 3)) + [npts - 1]:
    circ = plt.Circle(
        (xo[n], yo[n]), radius=ro, color="k", fill=True, clip_on=False, alpha=0.2
    )
    ax[0].add_patch(circ)
    
ax[1].plot(flux, 'k.')
```

And this is the output:
![image](https://user-images.githubusercontent.com/18243408/78397506-56948a00-75bf-11ea-83e4-24aa3d2667e9.png)

It's an edge case that probably doesn't matter for inference. I noticed it because I generate fake data from very high order maps.

Starry version:`'1.0.1.dev43+gf871d249'`

**Comment by rodluger** [comment]
Ok, thanks for finding this. Here's a slightly simpler version that shows the instability as a function of `k^2` (Equation D23 in [the paper](https://arxiv.org/pdf/1810.06559.pdf)):

```python
import starry
import matplotlib.pyplot as plt
import numpy as np
starry.config.lazy = False

map = starry.Map(ydeg=20, reflected=False)
map[1:, :] = 1
xo = np.logspace(-2, np.log10(2.0), 10000)
yo = 0
ro = 0.9
flux = map.flux(xo=xo, yo=yo, ro=ro)
bo = np.sqrt(xo ** 2 + yo ** 2)
ksq = (1 - ro ** 2 - bo ** 2 + 2 * bo * ro) / (4 * bo * ro)
plt.plot(ksq, flux)
plt.xscale("log")
plt.show()
```

![image](https://user-images.githubusercontent.com/9323819/78402450-9ad85800-75c8-11ea-814c-188ffe8a7d32.png)

Looks like things are bad for `k^2 > 1`, although the instability sets in a bit before that. My guess is the evaluation of the J integral (Equation D39) gets unstable. It might help to replace the upward/downward recursion with a tridiagonal solver. I'll look into it.

**Comment by ericagol** [comment]
@rodluger Do you need my help with this?

**Comment by rodluger** [comment]
@ericagol Thanks for offering! Let me take a look at it and get back to you. The simplest thing might be to just perform the troublesome integral numerically via quadrature. I've found this to be just as computationally efficient in some cases, and far less of a headache.

**Comment by rodluger** [comment]
@ericagol The instability is actually in the K integral ([Equation D36](https://arxiv.org/pdf/1810.06559.pdf)). I suspect there's some catastrophic cancellation going on when we apply Vieta's theorem. This seems to happen for high `l` and when `ro ~ 1`. As I decrease the occultor radius, the instability gets much weaker.

Here's what I get when I numerically integrate Equation (D36). There are still some oscillations when `ksq > 1` (looking into that), but things are way better. It might be useful to derive an upward/downward recursion relation for `K` itself (rather than for `I`), given boundary conditions evaluated numerically in this fashion. If you have time, can you look into that?

![image](https://user-images.githubusercontent.com/9323819/78674459-a5893a80-78b1-11ea-83d5-cfd4773c59e1.png)

**Comment by ericagol** [comment]
I'm wondering if this is a problem primarily for `bo ~ 0` and `ro ~ 1`.  There was a similar issue I faced in the Limbdark paper for computing the derivatives of the `P` integral (in section 6.2):

https://iopscience.iop.org/article/10.3847/1538-3881/ab4fee

I think the problem may have to do with `\delta ~ 0.5`, which could be causing the cancellations to occur for the Vieta's formula expansion.  One idea would be to look into the substitution `\sin^2\phi = (1-\cos{2\phi})/2`, and then create an alternate Vieta's expansion which would be in terms of `2\delta + 1` rather than `\delta`.  But, not sure if this would work...

I think a recursion formula for `K_{u,v}` and `L_{u,v}` would be difficult to derive since there are two dimensions (`u` and `v`).

**Comment by rodluger** [comment]
Yes, in this case the instability occurs as `delta` approaches `0.5`. I don't think we should spend too much time on this, since it's somewhat of an edge case. I was thinking we could do something like what we did in [Equation (D29)](https://arxiv.org/pdf/1810.06559.pdf) for the `H_{u,v}` function, which is also two dimensional. I'll poke around.

**Comment by rodluger** [comment]
Note: I added the special flag `STARRY_KL_NUMERICAL` to force numerical computation of the problematic integrals above `l = 15`. This will slow down the code, but may be useful if a high degree expansion is needed. Note that numerical instabilities will still kick in at some `l >~ 20`.

```bash
rm -rf build && STARRY_KL_NUMERICAL=1 python setup.py develop
```

**Comment by rodluger** [comment]
Punting on this for now. Feel free to reopen if a better solution is needed.
