### ISSUE TITLE
Question regarding the "Computing the intensity" portion of the The Basics

### ISSUE THREAD

**Issue by psaxena2** [rodluger/starry#247]
I'm going through the basics tutorial for starry (which I'm really excited to use for a number of different projects!) and am running into an issue I was hoping you had some advice on.

When I try to plot the intensity of the Earth along the equator, i get the following error (this is all from the python command line):

> Traceback (most recent call last):
> File "", line 1, in 
> File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2761, in plot
> return gca().plot(
> File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1646, in plot
> lines = [*self._get_lines(*args, data=data, **kwargs)]
> File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 216, in call
> yield from self._plot_args(this, kwargs)
> File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 332, in _plot_args
> y = _check_1d(tup[-1])
> File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/cbook/init.py", line 1325, in _check_1d
> if not hasattr(x, 'shape') or len(x.shape) < 1:
> TypeError: object of type 'TensorVariable' has no len()

I saw the Theano tutorial addresses this with the following: _Python requires that len returns an integer, yet it cannot be done as Theano’s variables are symbolic. However, var.shape[0] can be used as a workaround._

I was wondering whether that means I need edit the corresponding line in the file where the issue is arising and whether you have a recommendation on how to do that. Sorry if this is a simple question or something on my end (or if I've missed it in my search through past issues)!

Thanks
Prabal Saxena

**Comment by rodluger** [comment]
Hi @psaxena2, it sounds like the issue is that you're trying to plot a `theano` variable instead of a `numpy` array. I think you're running the example [here](https://rodluger.github.io/starry/latest/notebooks/Basics.html#Computing-the-intensity) but in **lazy** mode (`starry.config.lazy = True`), so the equatorial intensity `I` is a `theano` variable (just print it to check). In **lazy** mode, you have to call the `.eval()` method on variables to get their numerical value (see [this tutorial](https://rodluger.github.io/starry/v1.0.0/notebooks/LazyGreedy.html )).

Alternatively, set `starry.config.lazy = False` at the top of your script to force `starry` to compile everything ahead of time and return `numpy` arrays instead of `theano` variables. This will be much faster than calling `.eval()`. You can read more about when to use **lazy** mode in the tutorial I linked to above.

Hope this helps.

**Comment by psaxena2** [comment]
Yep - that worked, thanks!
