### ISSUE TITLE
Higher order limb darkening

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#36]
This is easy. Figure out the general expression for the nth order limb darkening coefficient in terms of the spherical harmonic coefficients and allow users to provide an array of mu coefficients when instantiating a Star object.

**Comment by ericagol** [comment]
As I mentioned, perhaps this should be a separate paper?

**Comment by ericagol** [comment]
Yes, I've been meaning to write some code to see which of the various expression/expansions gives the best accuracy and/or speed for different values of b & r.  It might also be interesting to include a limb-brightening term given in Schlawin et al.  And, it would be interesting to fit some stellar atmosphere limb-darkening models to see how many coefficients are needed to represent these accurately.  Another thing I've been thinking about is what to do about the derivatives at the contact points.  I think it is mainly the non-limb-darkened term that is the problem.  In practice, maybe this isn't a concern since it is a set of measure zero.  The final thing I would like to think about is whether there is a better way to time-integrate.  I looked back at the Gimenez (2006, A&A, 450, 1231;  DOI: 10.1051/0004-6361:20054445) to paper to compare your solution to his.  He computes the limb-darkened light curve up to \mu^N, and for each \mu^n for 0 < n <= N, he gives the solution in terms of an infinite series where each term in the series involves polynomials and Gamma functions.  It's cool that your solution does this all analytically in terms of three elliptic integrals and a polynomial!  It may, however, be worth comparing with his code for accuracy and/or speed.

**Comment by rodluger** [comment]
@ericagol 
Arbitrary order limb darkening is now implemented in starry! Here's a concocted example of fitting a 10th order limb darkening model to an 11-point stellar intensity grid to get an "exact" limb darkening model.
![image](https://user-images.githubusercontent.com/9323819/40285652-a23b3f3a-5c53-11e8-913a-39a11e22183e.png)
I'll write up all the math in the limb darkening paper this week.

**Comment by ericagol** [comment]
Excellent!  Do the higher order coefficients require a Taylor expansion in this case?

**Comment by rodluger** [comment]
Only when $b$ is very close to zero -- that's really the only unstable region for small occultors.

**Comment by ericagol** [comment]
That could possibly be fixed with using the generalized complete elliptic integrals.

**Comment by rodluger** [comment]
True! I'll play around with that.
