### ISSUE TITLE
s_n for m=-1; and possibly for other Y_lm values.

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#39]
I just noticed that s_n = 0 whenever m=-1.

This makes sense since in this case there is odd symmetry about the x-axis,
so the flux below the axis (y < 0) cancels with the flux of opposite sign
above the axis (y > 0).

We can either skip computing these, or perhaps use this as a check that the code is working fine?

This symmetry can also be used to check that m=1 is being computed correctly if
the occultor is placed on the y-axis (x=0).  A rotation needs to be made, but then
the resulting flux should be zero if the only non-zero Y_lm has m=1.

In addition, some other symmetries might be exploited as a check.  For b=0, some Y_lm values alternate between positive and negative flux around the origin, so these should give zero flux, I think.

**Comment by rodluger** [comment]
Nice find! It's somewhat more complicated than that, but you're right, several of the terms are zero. Because of the sleight-of-hand involved with the exterior derivatives, the n^th term in the Green's basis (which integrates to the n^th term of **s**) is not the same as the n^th spherical harmonic. What we need to find are terms in **g** that integrate to zero when the occultor is along the y axis (I align the occultor with the y axis, not the x axis, so it's the m = 1 harmonics that are in the null space). These are the terms with odd powers of x, which occur if and only if `(mu - 1) / 2` is odd in the last line of this equation:
![image](https://user-images.githubusercontent.com/9323819/39246136-0ca6cab6-486c-11e8-98fe-0e9d23b0fe2a.png)
I tried setting all of these integrals to zero and it worked! This should give us a bit of a speed gain.

Also, if I'm not mistaken, the occultation flux for all harmonics except the m = 0 ones is zero when b = 0! This is a good check for the code.
