### ISSUE TITLE
Gradients are NaN when b = 0

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#49]
```bash
>>> python -c "import starry; m = starry.grad.Map(); m[1,-1] = 1; print(m.flux(ro=0.1))"
[[ 0. nan nan nan nan nan nan nan]]
```

When `b = 0`, `ksq` is infinity and its derivatives are not defined. I tried overriding the computation of `ksq` for this case but wasn't able to fix the issue. This is an edge case, so not a huge deal, but would be nice to fix. We could easily bypass this by finding analytic closed-form expressions for the `s` vector when `b = 0`. Shouldn't be hard.

**Comment by rodluger** [comment]
Also getting NaNs for the gradient when `b = 1 - r`. There are probably a lot of these edge cases; I need to map them thoroughly.

**Comment by ericagol** [comment]
That is the one point where the gradient is in fact undefined!
I think this is due to the uniform disk terms since there is a step in
surface brightness at the limb.   The  other limb-darkening
terms \propto \mu^n approach zero surface brightness gradually
at the limb, so I think their derivatives should be well defined
and equal to zero.  Although, I'm primarily thinking of the m=0
cases;  the m != 0 cases may have also have discontinuities at
the disk boundary.

If you are evaluating a separate formula at that
point, you should be able to define the gradient as zero.

Physically, the surface brightness must gradually
go to zero - you can see this for limb-darkening of stars, for example,
in the recent paper by Claret, say Figure 6.   I haven't thought of a
dataset where it might be necessary to model this (the contacts are so
short in duration that there will little signal-to-noise to measure the
scale height of the surface brightness drop-off).  I've been thinking about
ways to possibly fix this...  but not sure if that would be necessary.

-Eric

**Comment by rodluger** [comment]
We are addressing this in #113.
