### ISSUE TITLE
Check my math

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#7]
Check the equations in the paper for typos and errors and comb through the Mathematica scripts to ensure my proofs and derivations are correct.

**Comment by deitrr** [comment]
Not sure if it ultimately matters, but I think you still need abs value signs around _m_ in Equation 3 (_m_<0 part): top of summation, inside _m_ choose _j_, exponent on _x_. Also in the first term, left of the brace.

**Comment by rodluger** [comment]
Yes, good catch, thanks!

**Comment by deitrr** [comment]
In Figure 2 and Equation 44, you have a rotation angle \omega, but you refer to this as \theta in the caption of Fig 2

**Comment by deitrr** [comment]
Also, I am struggling with producing the form of Equation 6. You've done some kind of transformation to change the indexing of the series, so that the _z_ exponent is _k_, no? I'm not worried about it--I've checked in mathematica that Equation 4 and 6 produce the same values, but I'm missing some key steps. In the attached image, Func1 is Equation 4 (unnormalized), Func2 is Equation 6, and Func3 is my result (as far as I could get). They appear to be equivalent, but I don't know how to transform Func3 into Func2. If this is just a symptom of my ignorance, then the text is probably fine as it is, but otherwise it might be worth being more explicit about how you did this in the text (and why). 
<img width="879" alt="screenshot 2018-03-27 13 42 58" src="https://user-images.githubusercontent.com/5489253/37965289-dcadd5e2-31c4-11e8-8a40-9fc930977194.png">

**Comment by rodluger** [comment]
Hmmmmm. I have absolutely no idea how I derived it! But I suspect that if you write
```
k' = l - 2k - m
```
and use the relation for [factorials of half-integers](https://en.wikipedia.org/wiki/Half-integer#Sphere_volume) you can get there.
Can you send me your derivation?

**Comment by deitrr** [comment]
Thanks, and sure, give me some time to tidy it up so that it is readable to other humans!

**Comment by ericagol** [comment]
I've checked most of the equations in D.2
